spring:
  datasource:
    url: jdbc:mysql://localhost:3306/data_jpa?createDatabaseIfNotExist=true
    username: learn
    password: 12345
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: mysql
    show-sql: true